#+title: yumi

A personal Guix channel

This channel contains mostly non-free software I personally use, which I could not find packaged anywhere else.

Programs provided by this channel:
- Renoise

* Installation

Add this channel to ~~/.config/guix/channels.scm~ like this:

#+begin_src scheme

(cons* (channel
        (name 'yumi)
        (url "https://github.com/senkowo/channel")
        ;; Enable signature verification:
        (introduction
         (make-channel-introduction
          "2517f6af408a5b4ad966f986ae8b9612a1280e21"
          (openpgp-fingerprint
           "864D 7D40 2260 D1A5 E9B9  AC9B B703 FEDE 1CF1 30EA"))))
       %default-channels)

#+end_src

* Renoise

Renoise is a non-free, modern, tracker-based DAW with demo and paid versions.

Homepage: https://www.renoise.com
Package definition: [[file:yumi/packages/renoise.scm][yumi/packages/renoise.scm]]

The =renoise= package, by default, pulls a copy of the demo-version installer from the Renoise website. 

** Installing the demo version

To install the demo version, you simply install the package as =renoise=.

** Install from a file

To install Renoise from an installer saved on your system (necessary for the paid/full version), you must apply a transformation to the package. This can be done in several ways:

*** Using command-line arguments

~$ guix install --with-source=renoise@<ver>=<path> renoise@<ver>~
(note the =renoise= after =--with-source==) 

This will install Renoise with version =<ver>= in the default profile using an installer found at =<path>=. The installer must be a =tar.gz= file.

An example, 
~$ guix install --with-source=renoise@3.4.3=/home/yui/Downloads/rns_343_linux_x86_64.tar.gz renoise@3.4.3~

Some more info:
- The =--with-source=renoise@<ver>== transformation essentially adds the file at =<path>= to the guix store, similar to =guix download=, but to be used for building the specified package.

*** Using Scheme

The following code applies the same transformation to the =renoise= package and provides it as =renoise-custom=. 

#+begin_src scheme

  (use-modules (gnu packages)
               (guix transformations))

  (define transform-install-path
    (options->transformation
     '((with-source
        . "renoise@3.4.3=/home/yui/Downloads/rns_343_linux_x86_64.tar.gz"))))

  (define-public renoise-custom
    (transform-install-path (specification->package "renoise@3.4.3")))

#+end_src

If you want to install this to the default profile, you could add ~renoise-custom~ to the end of the file, then run ~$ guix install -f <path-to-file>~.

Personally, I like to add it to a pre-existing manifest, like this:

#+begin_src scheme

  (define-public renoise-manifest
    (cons*
     renoise-custom
     (specifications->packages
      '(;; vv jack vv
        "jack" "jack2" "qjackctl"
        "dbus"
        "alsa-utils"
        "programming-socks"))))

#+end_src

**** Using a package variant

You have the option to create a package variant that performs the transformation and put it in your personal guix channel, but I wouldn't recommend it for several reasons... It makes debugging harder due to having a name similar to the original package, and relevant commands, like the ones in the following sections, are slightly different. But anyway, here's how you'd create a package variant that performs the transformation.

#+begin_src scheme

  (define transform-install-path
    (options->transformation
     '((with-source
        . "renoise@3.4.3=/home/yui/Downloads/rns_343_linux_x86_64.tar.gz"))))

  (define-public renoise-full-3.4.3
    (package
      (inherit
       (transform-install-path 
        (specification->package "renoise@3.4.3"))) ; make sure to specify version
      (name "renoise-full")))

#+end_src

** Prevent guix gc from deleting sources in store

If you installed Renoise from a local file, after running ~guix gc~, it may delete the sources from the guix store, requiring having to fetch the installer when rebuilding. When this happens, the package transformation will need to specify a valid path to the installer. But I personally prefer to delete the Renoise installer after installing it, just to wipe out any possibility of accidentally uploading my copy to somewhere. 

To prevent Guix from deleting the Renoise sources from the store, run the following:

~$ guix build --with-source@<ver>=renoise=<path> --root=<symlink-path> renoise@<ver>~

This will create a symlink at =<symlink-path>=, which points to the renoise package profile in the store. For as long as this symlink exists, =guix gc= will not remove the sources from the store. You should now be able to delete the Renoise installer in your home directory, without the fear of =guix gc= deleting the sources and having to re-fetch the installer.

*** If you created a package variant

If you created a Renoise package variant that applies the transformation, the command to run is a little bit different:

~$ guix build --with-source=renoise-full@<ver>=<path> --root=<symlink-path> renoise-full@<ver>~
(this is assuming the package name is =renoise-full=)

The package name specified after =--with-source== and at the very end must match your package variant's name.

* Contributing

I'm not extremely savvy with Guix or scheme, so let me know if there are any ways in which I can improve this channel! :3

For example:
- making available certain Renoise versions
- advice on writing package definitions

* References
- https://gitlab.com/guix-gaming-channels/games: on avoiding guix gc from deleting sources, and all around a great resource on non-free guix packages.

* Notes to self
- Does not specifying package version to transformation break things when the renoise package definition is updated?
- Create multiple package defs for different versions?
- Run guix git authenticate before any commits/pushes in master
- key branch
- Combine channel and config
  - private?
  - no, keep separate, so can write explaination of Guix on guix config, and at the bottom, have a link to the channel.
- Guix channel is the only thing that needs to be on github, bc it needs to last for +5years
- Keep codeberg for personal
